kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: bk8s
nodes:
- role: control-plane
  image: kindest/node:v1.32.0
- role: worker
  image: kindest/node:v1.32.0
networking:
  podSubnet: "10.246.0.0/16"
  serviceSubnet: "10.98.0.0/12"
